apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appointment-service.fullname" . }}-config
data:
  dbHost: {{ .Values.config.dbHost | quote }}
  dbPort: {{ .Values.config.dbPort | quote }}
  dbName: {{ .Values.config.dbName | quote }}
  dbUser: {{ .Values.config.dbUser | quote }}
  notificationServiceUrl: {{ .Values.config.notificationServiceUrl | quote }}